import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	metafile: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	const result = await context.rebuild();
	// 体积分析：写出 metafile 并打印进包字节数 Top 20（meta.json 已 gitignore）
	const fs = await import('node:fs');
	fs.writeFileSync('meta.json', JSON.stringify(result.metafile, null, 2));
	const jsOutput = Object.values(result.metafile.outputs).find(
		(o) => o.entryPoint,
	);
	const inputs = Object.entries(jsOutput.inputs)
		.map(([file, info]) => ({ file, bytes: info.bytesInOutput }))
		.sort((a, b) => b.bytes - a.bytes)
		.slice(0, 20);
	console.log('=== 进包字节数 Top 20 ===');
	for (const { file, bytes } of inputs) {
		console.log(`${String(bytes).padStart(8)}  ${file}`);
	}
	process.exit(0);
} else {
	await context.watch();
}
